### ISSUE TITLE
crash in "charts"

### ISSUE THREAD

**Issue by HaveFlight** [rybafish/rybafish#970]
The app has crashed with the following call-stack once I clicked on a partucular ABAP job to get its name:
![image](https://github.com/rybafish/rybafish/assets/167679983/353f82a5-5302-4208-863e-bbec865b0d95)

0.96 beta 1 is used.

**Comment by rybafish** [comment]
Thanks for reporting.

This bug was already fixed in beta II, please update:
https://github.com/rybafish/rybafish/releases/download/096bii/RybaFish_096betaII.7z

In case crash repeated please share the last lines of rybafish.log files
containing crash itself plus 10 seconds before crash.

Have a good one

**Comment by HaveFlight** [comment]
It's my mistake. We are using 0.96 beta 2 currently..

Here is the log:
![image](https://github.com/rybafish/rybafish/assets/167679983/ca91a199-8cb2-48d5-bb83-dcb282188f90)

**Comment by rybafish** [comment]
Please try [096betaIII](https://github.com/rybafish/rybafish/releases/download/096biii/RybaFish_096betaIII.7z) (not published on the site yet).

**Comment by HaveFlight** [comment]
Thanks for sharing!
If the bug reoccurres, I'll let you know.

**Comment by rybafish** [comment]
will publish on the site as soon as I fix the splash logo)
